(define anthy-utf8-widgets '(widget_anthy_utf8_input_mode))
(define default-widget_anthy_utf8_input_mode 'action_anthy_utf8_hiragana)
(define anthy-utf8-input-mode-actions '(action_anthy_utf8_hiragana action_anthy_utf8_direct))
(define default-widget_anthy_utf8_kana_input_method 'action_anthy_utf8_roma)
(define anthy-utf8-kana-input-method-actions '(action_anthy_utf8_roma))
